name = "cobblewiz"
author = "Metasura_"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b66e7276fcbd8b84ef6a87cce4d523aca9e83b9d54e353d85d652fbce963c1b7"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
